/**
 * Save component.
 *
 * Returns null on purpose: this is a dynamic block, so its front-end markup is
 * generated by render.php at request time rather than serialized into post content.
 * Returning null also means the block has no saved markup to invalidate, which
 * avoids block-validation errors when the render logic changes.
 */
export default function save() {
	return null;
}
